[workspace]
resolver = "3"
members = ["projects/*"]
default-members = [
    "projects/live2d-parser",
    "projects/live2d-runtime",
]
exclude = [
    "projects/lpk-gui",
    "projects/lpk-web",
    "projects/.DS_Store",
]


[workspace.package]
version = "0.0.0"

[profile.release]
lto = true
panic = "abort"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
